services:
  - type: web
    name: food-recognition-api
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: TORCH_HOME
        value: /opt/render/project/src/cache
